<a href="https://colab.research.google.com/github/Ellana555/Python_module2/blob/main/9_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Массив с данными учеников
students = np.array([
                     [1, 135, 34, 4],
                     [2, 160, 43, 5],
                     [3, 163, 40, 4.3],
                     [4, 147, 44, 5],
                     [5, 138, 41, 4.7],
                     [6, 149, 54, 3.9],
                     [7, 136, 39, 4.2],
                     [8, 154, 48, 4.9],
                     [9, 137, 35, 3.7],
                     [10, 165, 60, 4.6]])
#students = pd.DataFrame(students, columns=['ID (номер в журнале)', 'Рост, см',	'Масса тела, кг', 'Средний балл'])
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [ ]:
# Средняя успеваемость
mean = np.mean(students[:, -1])
print(mean)

4.430000000000001


In [ ]:
# Медиана
median = np.median(students[:,-1])
median

np.float64(4.449999999999999)

In [ ]:
sort = np.sort(students[:,-1])
sort

array([3.7, 3.9, 4. , 4.2, 4.3, 4.6, 4.7, 4.9, 5. , 5. ])

In [ ]:
(sort[4]+sort[5])/2

np.float64(4.449999999999999)

In [ ]:
mediana = np.median(students[:, 2])
mediana

np.float64(42.0)

In [ ]:
dif = np.mean(students[:, 2]) - np.median(students[:, 2])
dif.round(1)

np.float64(1.8)

In [ ]:
# Корреляция между ростом и весом
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [ ]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [ ]:
# Стандартное отклонение
std = np.std(students[:,1])
mean_rost = np.mean(students[:,1])
std
#mean_rost

np.float64(11.083320801997928)

In [ ]:
std = np.std(students[:,3])
std

np.float64(0.4517742799230607)

In [ ]:
# Дисперсия
var = np.var(students[:,2])
var

np.float64(60.36)